import org.jetbrains.kotlin.config.JvmTarget

/*
 * This file was generated by the Gradle "init" task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("org.springframework.boot") version "3.0.6"
    id("io.spring.dependency-management") version "1.1.0"
    kotlin("jvm") version "1.8.21"
    kotlin("plugin.spring") version "1.8.21"
    id("com.google.cloud.tools.jib") version "3.3.2"
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }

    maven {
        url = uri("https://jcenter.bintray.com/")
    }
}

dependencies {
    implementation(platform("org.springframework.boot:spring-boot-dependencies:3.0.6"))
    implementation("org.springframework.boot:spring-boot-starter-actuator")
    implementation("org.springframework.boot:spring-boot-starter-web")
    implementation("io.micrometer:micrometer-registry-prometheus")

    implementation("org.jetbrains.kotlin:kotlin-reflect:1.8.21")
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.8.21")
    implementation("com.fasterxml.jackson.module:jackson-module-kotlin:2.13.2")
    implementation("io.github.microutils:kotlin-logging:3.0.5")
    implementation("com.squareup.okhttp3:okhttp:4.11.0")

    //Test
    testImplementation("org.junit.jupiter:junit-jupiter:5.8.2")
    testImplementation("org.springframework.boot:spring-boot-starter-test")
    testImplementation("io.mockk:mockk:1.12.3")
}

group = "com.jm"
version = "0.0.1-SNAPSHOT"
description = "strava-token-generator"

tasks.withType<Test> {
    useJUnitPlatform()
}

kotlin {
    jvmToolchain {
        languageVersion.set(JavaLanguageVersion.of("19"))
    }
}

jib {
    to {
        image = "jmillnerdev/strava-token-generator"
    }
    from {
        image = "eclipse-temurin:19.0.2_7-jre-jammy"
        platforms {
            platform {
                os = "linux"
                architecture = "arm64"
            }
        }
    }
}