management:
  endpoints:
    prometheus:
      enabled: true
    web:
      exposure:
        include: ["*"]

spring:
  servlet:
    multipart:
      max-file-size: 10MB
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: Strava
  jackson:
    serialization:
      indent-output: true
      write-dates-as-timestamps: false
      fail-on-empty-beans: false
    deserialization:
      fail-on-unknown-properties: false

