management:
  endpoints:
    prometheus:
      enabled: true
    web:
      exposure:
        include: ["*"]

spring:
  servlet:
    multipart:
      max-file-size: 10MB
  jackson:
    serialization:
      indent-output: true
      write-dates-as-timestamps: false
      fail-on-empty-beans: false
    deserialization:
      fail-on-unknown-properties: false

strava:
  url: https://www.strava.com/oauth/authorize
  accessToken: ${STRAVA_ACCESS_TOKEN:pleasefillmein}
  clientId: ${STRAVA_CLIENT_ID:pleasefillmein}
  clientSecret: ${STRAVA_CLIENT_SECRET:pleasefillmein}
  OAuthUrl: https://www.strava.com/api/v3/oauth/token
